spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    initialization-mode: always
  liquibase:
    change-log: classpath:db/changelog/liquibase-changelog.xml